      - name: Run Docker Image to serve users
        run: |
          sudo docker rm -f medicalbot || true
          sudo docker pull "${{ steps.login-ecr.outputs.registry }}"/"${{ secrets.ECR_REPO }}":latest
          sudo docker run -d --name medicalbot -p 8080:8080 --env-file /home/ubuntu/.env \
          "${{ steps.login-ecr.outputs.registry }}"/"${{ secrets.ECR_REPO }}":latest
